"""updated book table

Revision ID: 1c0397094363
Revises: 766a2457f9fd
Create Date: 2024-12-14 00:33:52.905185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0397094363'
down_revision = '766a2457f9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['borrowed_by'], ['id'])
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('borrowed_by')

    # ### end Alembic commands ###
