"""updated books table

Revision ID: 2faa22272f5d
Revises: 81a7798c89d5
Create Date: 2024-12-14 01:31:07.919274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2faa22272f5d'
down_revision = '81a7798c89d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_book_borrowed_by', 'user', ['borrowed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_borrowed_by', type_='foreignkey')
        batch_op.drop_column('borrowed_by')

    # ### end Alembic commands ###
