"""updated books table

Revision ID: 30c5e12f968f
Revises: 98fb393ff469
Create Date: 2024-12-14 00:58:09.010179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c5e12f968f'
down_revision = '98fb393ff469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['borrowed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('borrowed_by')

    # ### end Alembic commands ###
