"""updated books table

Revision ID: 6b5e43fe5f66
Revises: 2faa22272f5d
Create Date: 2024-12-14 02:25:47.839711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5e43fe5f66'
down_revision = '2faa22272f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('checkout_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('checkout_date')
        batch_op.drop_column('returned')

    # ### end Alembic commands ###
