"""Added rating attribute to books

Revision ID: 766a2457f9fd
Revises: b838ad2033ce
Create Date: 2024-12-13 19:51:48.807591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766a2457f9fd'
down_revision = 'b838ad2033ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
