"""updated books table

Revision ID: e8ad0cc11ba5
Revises: 6b5e43fe5f66
Create Date: 2024-12-14 10:55:48.774616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ad0cc11ba5'
down_revision = '6b5e43fe5f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('checkout_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
